services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:4.2
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pets
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass12345
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 30s
      timeout: 10s
      retries: 5

  # nginx:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx_set/nginx.conf:/etc/nginx/conf.d/default.conf 
  #     - ./app/static:/usr/share/nginx/html/static
  #   depends_on:
  #     - app

volumes:
  mongodb-data:
