services:
  app:
    build: .
    # expose:
    #   - 5000
    ports:
      - 5000:5000
    depends_on:
      mongo:
        condition: service_healthy
    links:
      - mongo

  mongo:
    image: mongo:4.2
    hostname: test_mongodb
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pets_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass12345
    volumes:
      - mongodb-data:/data/db
      - ./app/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build: ./nginx_set
    restart: always
    ports:
      - "80:80"
    volumes:
      # - ./nginx_set/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./app/static:/usr/share/nginx/html/static
      # - ./app/templates/index.html:/usr/share/nginx/html/templates
    depends_on:
      - app

volumes:
  mongodb-data:
